language: go

dist: trusty

go:
- "1.10"

env:
  - MY_GOOS=linux MY_GOARCH=amd64 DEP_VERSION=0.4.1
  - MY_GOOS=darwin MY_GOARCH=amd64 DEP_VERSION=0.4.1
  - MY_GOOS=windows MY_GOARCH=amd64 DEP_VERSION=0.4.1

cache:
  directories:
    - $GOPATH/pkg/dep

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - export GOOS=${MY_GOOS}
  - export GOARCH=${MY_GOARCH}
  - export CGO_ENABLED=0

script:
  - go build -ldflags "-s" github.com/exoscale/terraform-provider-exoscale
  - >
    if [ "${MY_GOOS}" = "linux" ] &&
       [ "${TRAVIS_GO_VERSION}" = "1.10" ] &&
       [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      TF_ACC=1 go test -v;
    fi
